/* eslint-disable no-unused-vars */
const { Config } = require("tailwindcss");
const { stylePreset } = require("./src/styles/preset");

/** @type {import('tailwindcss').Config} */
const config = {
  content: ["./src/**/*.{ts,tsx,js,jsx,php}"],
  presets: [stylePreset],
  safelist: [
    "flex",
    "flex-1",
    "flex-wrap",
    "font-bold",
    "h-10",
    "h-4",
    "h-5",
    "items-center",
    "justify-center",
    "label",
    "leading-5",
    "leading-none",
    "list-none",
    "m-0",
    "mb-3",
    "mb-4",
    "mb-6",
    "md:ml-3",
    "md:mr-8",
    "md:order-1",
    "ml-0",
    "ml-auto",
    "mr-5",
    "mr-[10px]",
    "mt-0",
    "mt-4",
    "my-auto",
    "order-2",
    "pl-0",
    "px-4",
    "py-3",
    "rotate-[-13.41deg]",
    "rounded-xl",
    "text-4xl",
    "text-base",
    "text-danger",
    "text-sm",
    "text-success/70",
    "text-white",
    "w-10",
    "w-4",
    "w-5",
    "w-full",
  ],
};

module.exports = config;
